# Generated by Django 4.2.3 on 2023-07-19 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('folder', '0002_folder_is_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('status_access', models.BooleanField()),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('author_user', models.CharField(max_length=20)),
                ('update_user', models.CharField(max_length=20)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='folder.folder')),
            ],
        ),
    ]
