# Generated by Django 4.2.3 on 2023-07-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_remove_page_status_access_pageaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='update_user',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
