# Generated by Django 4.2.3 on 2023-07-20 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('page', '0003_alter_page_update_user'),
        ('folder', '0004_delete_entryaccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('text', models.CharField()),
                ('entry_status', models.CharField(max_length=11)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('author_user', models.CharField(max_length=20)),
                ('update_user', models.CharField(max_length=20, null=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='page.page')),
            ],
        ),
        migrations.CreateModel(
            name='EntryLink',
            fields=[
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='entry.entry')),
                ('text', models.CharField()),
                ('url', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='EntryAccess',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=50)),
                ('entry_access_status', models.CharField(max_length=7)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='folder.folder')),
            ],
        ),
    ]
