# Generated by Django 4.2.3 on 2023-07-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrylink',
            name='url',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
