# Generated by Django 4.2.3 on 2023-07-18 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('status_access', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PageAccess',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=50)),
                ('page_access_status', models.CharField(max_length=7)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='folder.folder')),
            ],
        ),
        migrations.CreateModel(
            name='FolderAccess',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=50)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='folder.folder')),
            ],
        ),
        migrations.CreateModel(
            name='EntryAccess',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=50)),
                ('entry_access_status', models.CharField(max_length=7)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='folder.folder')),
            ],
        ),
    ]
