# Generated by Django 4.2.3 on 2023-07-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
